version: "3.8"
services:
  invoicing-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./bin:/var/www/public
