version: "3.8"
services:
  invoicing-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./bin:/var/www/public
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "9411:9411"
      - "16686:16686"
